### ISSUE TITLE
Інструкція па запуску праекта ды рэдмі

### ISSUE THREAD

**Issue by itbeard** [bel-frontend/bel-frontend.github.io#26]
Было б выдатна пабачыць:
- Крыху больш пашыраны рэдмі, са спасылкай на сам сайт, з невялкім апісанне тэхналогій і фрэймваркаў у кодзе
- Не хапае ліцэнзіі (каб потым не было праблем)
- Моцна не хапае у рэдмі ці у Вікі апісання таго, як наладзіць праект лакальна ды запусціць. Выдата наогул былоб мець докер-кантэйнер і каманду на яго запуск
- Дзяк за працу!

**Comment by bel-frontend** [comment]
Так, дакументацыю   я  ў хуткім часе  дадам.  Наконт ліцэнзіі -  якую лепей  браць?
