### ISSUE TITLE
SSR каб можна было знайсці кантэнт у пашукавіках

### ISSUE THREAD

**Issue by ilyaryabchinski** [bel-frontend/bel-frontend.github.io#27]
Сайт мае шмат статычнага кантэнту, таму мне падаецца, што будзе добра калі гэты кантэнт будзе індэксавацца пашукавымі ботамі. Дзеля гэтага можна напісаць невялічкі node.js-сервер ці міграваць на Next.js. Але гэта адразу зробіць дэплой больш складаным. Што думаеш наконт гэтага? Велізарны дзякуй за працу!❤️

**Comment by bel-frontend** [comment]
ну дэплой-  гэта меньшае з зол.  на нэкст магчыма  бдузем міграваць)  але  зараз  пакуль думаю крыху навеці дызайн ды інш. Дарэчы гугл ужо працуе з сайтам  і  зараз  у выдачы есць нашыя артыкулы (бо іншых  і няма увогуле)

**Comment by ilyaryabchinski** [comment]
калі патрэбна дапамога з міграцыяй на нэкст - буду рады дапамагчы!

**Comment by ilyaryabchinski** [comment]
https://astro.build дарэчы таксама неблагі варыянт 🤔

**Comment by vaukalak** [comment]
мяркую OS праэкту лепш карыстацца найбольш папулярным рухавіком, таму +1 да next.js

**Comment by ilyaryabchinski** [comment]
Так next.js для вялікай колькасці каманд па сутнасці дэфолтны выбар, але astro зараз вельмі цудоўна развіваецца, ды ўжо ў вельмі добрым ды стабільным стане, таму я б не адкідваў яго адразу 🤔

**Comment by zavsievich** [comment]
Праблема Next.js: складана дэплоіць без vercel, могуць быць праблемы з app router (таму што тэхналогія сырая) і ўцечкі памяці (таму што next заменчаны пад інфраструктуру vercel). Мае прапанаванні: Astro, Remix, Qwik City
