### ISSUE TITLE
Назва кнопкі для скасавання адпраўкі паведамлення аб памылцы

### ISSUE THREAD

**Issue by zubialevich** [bel-frontend/bel-frontend.github.io#29]
Вітаю! 
Па-першае Дзякуй за такую ініцыятыву!

Па-другое, звычайна кнопку “Cancel” па-беларуску падпісваюць як "Скасаваць".
З гласарыя гугл: 
Cancel - Скасаваць (To revoke an action. To quit an action without saving any changes that the action would result in.

**Comment by bel-frontend** [comment]
выпраўлена
