### ISSUE TITLE
Форма адпраўкі паведамлення пра памылку не закрываецца

### ISSUE THREAD

**Issue by zubialevich** [bel-frontend/bel-frontend.github.io#30]
Форма адпраўкі паведамлення пасля націскання на кнопка "Адправіць" здаецца нічога не робіць. Застаецца ў адкрытым стане.
Калі яна працуе, то прабачце за колькасць паведамленняў :)

**Comment by bel-frontend** [comment]
цікавы момант)  ці есць адказ сервера?

**Comment by bel-frontend** [comment]
Дадаў натыфікацыю  для таго как паказваць статусы  запытаў на сервер

**Comment by zubialevich** [comment]
Зараз больш відавочна, што адбылося. Але форма пасля адпраўкі паведамлення не ачышчаецца. І, можа мне так пашчасціла, але форму можна адправіць толькі адзін раз - пасля гэтага трэба абнавіць старонку

**Comment by bel-frontend** [comment]
так  ,я   праверыў, ды паправіў  ачыстку формы. зараз павінна працаваць)

пн, 27 мар. 2023 г. в 12:44, Dzmitry Zubialevich ***@***.***>:

**Comment by zubialevich** [comment]
Дзякуй!)
