### ISSUE TITLE
Немагчыма стварыць акаунт

### ISSUE THREAD

**Issue by uladz-zubrycki** [bel-frontend/bel-frontend.github.io#40]
### Праблема
- HTTP 400 пры спробе рэгістрацыі з валідным і-мэйлам;
- Папап з памылкай выглядае незразумела;

### Дэталі
[Відэа](https://onedrive.live.com/?authkey=%21AFJ06yZB5fLroGk&cid=E138E16A8D483D03&id=E138E16A8D483D03%21745080&parId=E138E16A8D483D03%21744258&o=OneUp)

#### Запыт
```
POST /register HTTP/1.1
Host: api.bel-frontend.online
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0
Accept: application/json, text/plain, */*
Accept-Language: be,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate, br
Content-Type: application/json
Content-Length: 62
Origin: https://bel-frontend.online
DNT: 1
Connection: keep-alive
Referer: https://bel-frontend.online/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
Sec-GPC: 1
Pragma: no-cache
Cache-Control: no-cache

{"email":"heigafv1@anonaddy.me","password":"UlQota4t$DZz!qEg"}
```
#### Водгук
```
HTTP/1.1 400 Bad Request
Date: Wed, 12 Apr 2023 18:06:38 GMT
Server: Apache/2.4.41 (Ubuntu)
vary: Origin
access-control-allow-origin: *
content-length: 0
Via: 1.1 api.bel-frontend.online (Apache/2.4.41)
Connection: close
```

#### Памылкі ў кансолі
```
Object { statusText: "Bad Request", status: 400, response: {…} } apiWatchRequest.js:170:13

<empty string> index.tsx:63:36
    onFailure index.tsx:63
    p Redux
    w runtime.js:62
    _invoke runtime.js:296
    t runtime.js:114
    Redux 37
    onSubmit index.tsx:55
    X Formik.tsx:849
    so Formik.tsx:1200
    q Formik.tsx:756
    (Async: promise callback)
    q Formik.tsx:731
    so Formik.tsx:1200
    G Formik.tsx:823
    so Formik.tsx:1200
    React 11

```
#### Магчымыя прычыны
Хутчэй за ўсё выкарыстоўваецца невалідны рэгексп для валідацыі адрасоў. 

Звычайна дастаткова праверыць, што
- і-мэйл не пусты;
- змяшчае `@`;
- сімвал `@` не першы і не апошні;

А замест складаных правілаў валідацыі выслаць ліст па адрасе.

**Comment by bel-frontend** [comment]
Цікава  што карыстальнік з такім мэйлам зарэгістраваны.

**Comment by uladz-zubrycki** [comment]
@bel-frontend магчыма мае, разоў 9 мог і паспець паспрабаваць з рознымі крэдамі. Усюды 400 было, таму гіпотэза з рэгекспам няслушная, але ж і зарэгістравацца не атрымалася.

Паглядзіце самі з данымі, што я тут пакінуў.

**Comment by bel-frontend** [comment]
так. я  пафіксіў.  можна рэгістравацца.  але трэба дадаць канфірм для емэйлаў. зраблю гэта  праз  іншую таску. Дзякуй за дапамогу.
