### ISSUE TITLE
Непатрэбнае абмежаванне на даўжыню пароляў

### ISSUE THREAD

**Issue by uladz-zubrycki** [bel-frontend/bel-frontend.github.io#41]
### Праблема
- Абмежаванне на даўжыню пароля 16 сімвалаў, у якім няма рэальнай патрэбы, але якое пагаршае UX;
- Памылкі нелакалізаваныя.

![image](https://user-images.githubusercontent.com/5411526/231550120-38dfae6f-3ecd-47f7-b400-7d339886258d.png)

**Comment by bel-frontend** [comment]
Зроблена
