### ISSUE TITLE
Калі ласка дадайце RSS да сайта

### ISSUE THREAD

**Issue by hleb-kastseika** [bel-frontend/bel-frontend.github.io#43]

**Comment by bel-frontend** [comment]
Дзень добры! Абавязкова дададзім.! Дзякуй за нагоду. Не абацаю што хутка.
але  думаю зробім.

ср, 24 мая 2023 г. в 20:37, Hleb Kastseika ***@***.***>:

**Comment by hleb-kastseika** [comment]
Дзякуй!

**Comment by bel-frontend** [comment]
> Дзякуй!

Няма за што)
