### ISSUE TITLE
Палепшыць картку для сацыяльных сетак

### ISSUE THREAD

**Issue by AGulev** [bel-frontend/bel-frontend.github.io#52]
Картка для сацыяльных сетак заўсёды выкарыстоўвае тэкст і відарыс сайта а не артыкула, калі спасылка менавіта на артыкул. Было б добра калі б для яе браўся першы відарыс артыкула ды яго назва

![IMG_0ADB3EE7AD67-1](https://github.com/bel-frontend/bel-frontend.github.io/assets/2209596/53363a83-6325-46c8-a411-48c7b4d83ae9)

**Comment by bel-frontend** [comment]
Так, Леш. я ведаю пра праблему.    пакуль не перайшлі на рэндэрынг на  серверы. Таму пакуль не працуе.

**Comment by bel-frontend** [comment]
так як мы пераехалі на нэкст -  павінна пачаць працаваць.  -відарыс пакуль не зрабілі -  есць цяжкасці, але  назва ды  метаданыя падцягваюцца

**Comment by bel-frontend** [comment]
з Відарысам -  пакуль  адкладваем - тут трэба на серверы прырэндар рыхтаваць.   навзву - так, дадаў
