### ISSUE TITLE
Нерэчаісны дамэн ў спасылках RSS

### ISSUE THREAD

**Issue by viachaslavic** [bel-frontend/bel-frontend.github.io#56]
### Бягучыя паводзіны

Стужка дагэтуль ўтварае спасылкі на bel-frontend.online.

### Пажаданыя паводзіны

Адпаведныя спасылкі на https://bel-geek.com/ у стужцы RSS.

**Comment by bel-frontend** [comment]
Так! Усё. Выправіў. Дзякуй за заўвагу
